server:
  port: 8080
  servlet:
    context-path: /demoWeek2

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/demoweek2"
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
